import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import AuthGuard from "@/components/AuthGuard";

// Geist fonts without the variable property
const geistSans = Geist({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
});

// Poppins font without the variable property
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <head>
        {/* No need for the Google Fonts <link> tag */}
      </head>
      <body
        className={`${poppins.className} antialiased`} // Use the className property from fonts
      >
        <SessionWrapper>
          <AuthGuard>
            {children}
          </AuthGuard>
        </SessionWrapper>
      </body>
    </html>
  );
}
